### ISSUE TITLE
Unknown type cowboy_router:route_match

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [inaka/cowboy_swagger#115]
Hi.

I'm running cowboy_swagger 1.2.3 with cowboy 1.1.2.

Static (dialyzer) analysis shows that cowboy_swagger trails.erl uses type cowboy_router:route_match(), which is not exported from cowboy 1.1.2's cowboy_router.

I don't know what cowboy version cowboy_swagger assumes for -spec().ing purposes, but I supposed (probably wrongly) that 2.x from cowboy_swagger would use 2.x from cowboy, for which the previous would be incompatible.

Would you be open to a support patch for 1.2.3 that fixes that issue?

Thanks.

**Comment by elbrujohalcon** [comment]
We sure am. Send that PR our way, @paulo-ferraz-oliveira !! Thank you in advance :)

**Comment by paulo-ferraz-oliveira** [comment]
I'd require a support branch (in the sense of git-flow, something like support/1.x) from c1258a1, though. Is that possible?

I'll do static analysis on 2.x to see if it suffers from a similar issue.

**Comment by elbrujohalcon** [comment]
Let me add you as a collaborator to this repo…

**Comment by elbrujohalcon** [comment]
Done! Go ahead and create branches! :)

**Comment by paulo-ferraz-oliveira** [comment]
👍 thanks.

I'm passing `xref` and `dialyzer` on both `cowboy_trails` and `cowboy_swagger` for OTP **19.3**, **20.3** and **21.2**. I (locally) changed `rebar.config` a bit (in both projects) to have my usual `xref` and `dialyzer` options. Will post results here, soon.

**Comment by paulo-ferraz-oliveira** [comment]
**cowboy_trails**
- with `rebar3 xref`, shows `trails_handler: 1 unresolved call` (I've never seen this before!),
- on OTP 21.2, has multiple compile-time warnings, related to `cowboy` and `ranch`,
- does not show other `xref` warnings,
- does not show other `dialyzer` warnings,
- with the remote `rebar.config`

**Comment by elbrujohalcon** [comment]
`unresolved call` means "there is a dynamic call in there". Likely [this one](https://github.com/inaka/cowboy-trails/blob/d8e34e7861f2cd94ed4b08c7893c5db02f798091/src/trails_handler.erl#L13), which is fine since it is a behavior after all.

**Comment by paulo-ferraz-oliveira** [comment]
> `unresolved call` means "there is a dynamic call in there". Likely [this one](https://github.com/inaka/cowboy-trails/blob/d8e34e7861f2cd94ed4b08c7893c5db02f798091/src/trails_handler.erl#L13), which is fine since it is a behavior after all.

But I've had dynamic calls in the past (for behaviours and not only) and I've never seen this warning.

**Comment by elbrujohalcon** [comment]
No idea, but that's also the only line of _actual code_ in that module anyway. 🤷‍♂️

**Comment by paulo-ferraz-oliveira** [comment]
**cowboy_swagger**
* has a deprecation warning, related to `cowlib`,
* on OTP 21.2, has multiple compile-time warnings, related to `cowboy` and `ranch`,
* does not show other `xref` warnings,
* does not show other `dialyzer` warnings,
* with the remote `rebar.config` we get a bunch of `unused export`s (from `xref`) but that's fine!

**Comment by paulo-ferraz-oliveira** [comment]
combo `cowboy` master / `cowboy_swagger` master
- shows no warnings for `xref` and `dialyzer`, with OTP **19.3**, **20.3** or **20.2** [I'm using 19+ because `cowboy` 2.x dropped support for 18.x], which means that once I migrate I won't have an issue anymore :D...

... but until I do, I'd like to PR `trails` (sorry, I though the issue was in `cowboy_swagger`, since I don't use `trails` directly).

**Comment by elbrujohalcon** [comment]
I'll add you as a collaborator there, as well.

**Comment by elbrujohalcon** [comment]
Done! :)

**Comment by paulo-ferraz-oliveira** [comment]
I can't seem to be able (403) to push to origin/upstream. We're talking about https://github.com/inaka/cowboy-trails, right?

**Comment by paulo-ferraz-oliveira** [comment]
This is what I'm proposing for support/0.x: https://github.com/paulo-ferraz-oliveira/cowboy-trails/tree/support/0.x

**Comment by paulo-ferraz-oliveira** [comment]
> No idea, but that's also the only line of _actual code_ in that module anyway. 🤷‍♂️

It's due to `xref_warnings`. I'd never used it before.

**Comment by elbrujohalcon** [comment]
Cool. You should accept your invite at https://github.com/inaka/cowboy-trails/invitations

**Comment by elbrujohalcon** [comment]
[This changes](https://github.com/inaka/cowboy-trails/compare/f76d0b5...paulo-ferraz-oliveira:support/0.x?expand=1) look good to me, BTW.

**Comment by paulo-ferraz-oliveira** [comment]
Here's what I'll propose for support/1.x: https://github.com/paulo-ferraz-oliveira/cowboy_swagger/tree/support/1.x

I need a minor rebar.lock update as soon as trails is hex-published, though.

**Comment by elbrujohalcon** [comment]
…and now it's published :)

**Comment by paulo-ferraz-oliveira** [comment]
@elbrujohalcon: do you think we can/should close this thread?

**Comment by elbrujohalcon** [comment]
Closing it!
