### ISSUE TITLE
cowboy and ranch version not compatible ?

### ISSUE THREAD

**Issue by zmstone** [inaka/cowboy_swagger#130]
What's the reason to use ranch 2.0.0 while cowboy 2.8.0 actually depend on ranch 1.7.1 ?
I believe the example app is having various issues due to this

**Comment by elbrujohalcon** [comment]
That's most likely true, but since we're not actively maintaining this project that much anymore… it might take a while until it's fixed.

That is… unless you feel like submitting a PR 😉

**Comment by paulo-ferraz-oliveira** [comment]
I bumped ranch in https://github.com/inaka/cowboy_swagger/pull/126, pretty sure due to static analysis issues. Tests didn't complain. Running this in production didn't either, so I assumed everything was Okay. It is possible the example app is either not being tested or not updated properly (I don't remember having looked at it). Pull requests are accepted, though 😉

**Comment by zmstone** [comment]
> That's most likely true, but since we're not actively maintaining this project that much anymore… it might take a while until it's fixed.
> 
> That is… unless you feel like submitting a PR 😉

We are trying to adopt cowboy_swagger in our project. May I ask why you have stopped (actively) maintaining it?

**Comment by zmstone** [comment]
> I bumped ranch in #126, pretty sure due to static analysis issues. Tests didn't complain. Running this in production didn't either, so I assumed everything was Okay. It is possible the example app is either not being tested or not updated properly (I don't remember having looked at it). Pull requests are accepted, though 😉

I will try to test it again and get back to you with the incompatible parts.

**Comment by zmstone** [comment]
for example: `{connection_type, supervisor}` leaked down to inet as socket options, resulting in this crash:
```
=CRASH REPORT==== 26-May-2021::16:36:33.466341 ===
  crasher:
    initial call: supervisor:ranch_acceptors_sup/1
    pid: <0.471.0>
    registered_name: []
    exception exit: badarg
      in function  inet_tcp:listen/2 (inet_tcp.erl, line 142)
      in call from ranch_acceptors_sup:start_listen_socket/4 (ranch_acceptors_sup.erl, line 78)
      in call from ranch_acceptors_sup:start_listen_sockets/5 (ranch_acceptors_sup.erl, line 54)
      in call from ranch_acceptors_sup:init/1 (ranch_acceptors_sup.erl, line 34)
      in call from supervisor:init/1 (supervisor.erl, line 301)
      in call from gen_server:init_it/2 (gen_server.erl, line 417)
      in call from gen_server:init_it/6 (gen_server.erl, line 385)
    ancestors: [<0.459.0>,ranch_sup,<0.442.0>]
```
