### ISSUE TITLE
Fix current resource path `/api-docs` according with Swagger 2.0 conventions (`/swagger.json`)

### ISSUE THREAD

**Issue by cabol** [inaka/cowboy_swagger#19]
Fix trails routes for:
- Static content (Swagger-UI). What should be the path here? We should avoid any routes conflicts.
- `cowboy_swagger_handler`. The path here should be `/swagger.json` directly.

NOTE: The idea is let that path totally configurable, as an environment variable of the app, and default value would be `/`.

**Comment by paulo-ferraz-oliveira** [comment]
@elbrujohalcon: does this issue still make sense? I can work on it, if so (I don't fully understand what needs to be done, but...). Otherwise, should we close it (it's been more than 5 years, already).

**Comment by elbrujohalcon** [comment]
…aaaaand closed!
