### ISSUE TITLE
The `cowboy_swagger_handler` should return also `swagger.yaml`.

### ISSUE THREAD

**Issue by cabol** [inaka/cowboy_swagger#20]
Modify `cowboy_swagger_handler` to return either `swagger.json` or `swagger.yaml`.

**Comment by paulo-ferraz-oliveira** [comment]
Related to https://github.com/inaka/cowboy_swagger/issues/19.

**Comment by paulo-ferraz-oliveira** [comment]
By "return" do you mean "serve", under route "https://SERVER:443/swagger.yaml", for example? If it's just that, it should be an easy fix. @elbrujohalcon, do you have input on this?

**Comment by elbrujohalcon** [comment]
@paulo-ferraz-oliveira this is a very very very old issue. For many years, nobody asked for it. I'll close it now and if somebody needs this functionality in the future, they may open a new ticket.
