### ISSUE TITLE
Consider upgrading to cowboy 2 API

### ISSUE THREAD

**Issue by jeanparpaillon** [inaka/cowboy_swagger#49]
I've created a branch for upgrading to new cowboy 2 API:
https://github.com/jeanparpaillon/cowboy-swagger/tree/cowboy2

**Comment by elbrujohalcon** [comment]
@Euen you might be interested in this effort :)

**Comment by jeanparpaillon** [comment]
@elbrujohalcon @Euen Just rebased the branch.

**Comment by elbrujohalcon** [comment]
Thanks @jeanparpaillon :)
We're waiting until the official release of cowboy 2.0 to migrate all of our libraries, including this one and cowboy-trails.
But, before that, we will most likely migrate from erlang.mk to rebar3 and start using hex.pm versions of the libraries. So, we'll also have to wait until cowboy 2.x is published to hex.pm.

Tiny comment: In your branch you have a `gPROJECT` in your Makefile.

**Comment by robertoaloi** [comment]
Any updates on this?
