### ISSUE TITLE
Update cowboy-swager dependency version in the example

### ISSUE THREAD

**Issue by cabol** [inaka/cowboy_swagger#50]
Currently, the example (https://github.com/inaka/cowboy-swagger/tree/master/example), is pointing to an old version of cowboy-swagger (`0.0.1`). The idea is point to the latest one.

**Comment by ferigis** [comment]
I think that one can be closed, it is already using the version 1.1.0 from  hex, which is the last working version.

**Comment by elbrujohalcon** [comment]
Got it.
