### ISSUE TITLE
Add support to others json libraries

### ISSUE THREAD

**Issue by joaohf** [inaka/cowboy_swagger#52]
It's possible to use another json library instead of jiffy?

Maybe the user could set it during the runtime or compile time.

Thanks.

**Comment by paulo-ferraz-oliveira** [comment]
`jiffy` is no longer being used. `jsx` is now the default.

**Comment by elbrujohalcon** [comment]
Another very old issue… I guess, @joaohf just moved on considering that we didn't reply in time 😞 .
