### ISSUE TITLE
CowboySwagger should support either binaries or io_lists for descriptions

### ISSUE THREAD

**Issue by HernanRivasAcosta** [inaka/cowboy_swagger#67]
Right now, it only accepts strings that it checks with `io_lib:printable_list/1`

**Comment by elbrujohalcon** [comment]
It's already working as good as it can possible work.
If anything, I would go exactly the other way: I would only accept binaries.
But as it is now, swagger understands both binaries and printable lists as json strings.
That's more than enough.
